### ISSUE TITLE
EFK-Launcher sous linux

### ISSUE THREAD

**Issue by H2L29** [ChristopheTdn/EFK-Launcher#1]
salut, j'ai tenté de lancer EFK Launcher sous debian sid : 
```
:~/EFK-PZ mod$ ./EFK\ Launcher 
[1559678] Error loading Python lib '/tmp/_MEI9et0M4/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEI9et0M4/libpython3.11.so.1.0)

```

**Comment by ChristopheTdn** [comment]
peux tu me donner la version de ta GLIBC ?
Le fait que tu soit sur une release instable indique peut etre les raison de cette incompatibilité...
J ai compilé cet executable sur Ubuntu Ubuntu 22.04.3 LTS
En revanche, j ai deja eue un retour pour des probleme similaire et corriger cette erreur est importante.
Merci pour tes retours.
Au pire, je te donnerai le moyen de compiler toi meme le programme pour avoirune version fonctionnel dans ton environnement

**Comment by H2L29** [comment]
j'ai ça mais j'suis pas sûr si c'est ce que tu veux
```

:~$ apt policy libc6
libc6:
  Installé : 2.37-13
  Candidat : 2.37-13
 Table de version :
     2.38-4 1
          1 http://deb.debian.org/debian experimental/main amd64 Packages
 *** 2.37-13 990
        990 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ChristopheTdn** [comment]
après investigation, j ai compilé l exécutable pour une version trop récente de Linux pour permettre une compatibilité avec cette sacré librairie. En l état ca revient a modifier tout mon environnement de dev pour le faire aller sur une version plus ancienne... 
ou alors essaye de mettre a jour ta librairie a la version 2.38-4 1 comme indiqué sur ta table de version

**Comment by H2L29** [comment]
comme je t'ai dit sur discord j'ai déjà eu des grosses galères avec libc6. le dernier chiffre (1) c'est la priorité dans ma table de version, c'est la priorité la plus basse parce que la version n'est vraiment pas prête à être utilisée en prod (experimental) du coup je préfère attendre un peu qu'elle passe d'elle même en unstable (SID) c'est la version la plus à jour de debian qui soit utilisable au quotidien :)

ne pourrais tu pas, toi, intégrer les libs de ton environnement avec ton executable? pour que ta version soit le plus portable possible.

**Comment by ChristopheTdn** [comment]
malheureusement la  libc6 semble etre un element specifique a chaque system et meme si la compatibilité avec les versions futures est (normalemen) assurée, il y a pas mal de pb.
Dans les faits, je devrais installé sur mon poste de dev une version plus ancienne de Ubunutu pour permettre de pouvoir comiler avec une libc6 plus ancienne et obtenir ainsi une plus grande compatibilité.
